version: '3.7'

services:

  frontend:
      build:
        context: frontend
      container_name: budget-web-app
      volumes:
        - './frontend:/app'
        - './frontend/node_modules:/app/node_modules'
      ports:
        - 4200:4200
      restart: on-failure
    
  django:
    build:
        context: backend
    container_name: budget-app
    ports: 
      - 8000:8000
    volumes:
      - ./backend:/app
    command: sh -c "python ./app/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres
    container_name: budget-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD