# Generated by Django 3.1.4 on 2021-01-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Account',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
